version: "3"

services:
  nextjs:
    image: sunilrudrakumar/nextjs-app:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/bitcoin_explorer

  rust_ingestion:
    image: sunilrudrakumar/rust-ingestion:latest
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bitcoin-explorer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
