version: "3"

services:
  nextjs:
    image: your-dockerhub-username/nextjs-app:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://your_user:your_password@postgres:5432/bitcoin_explorer

  rust_ingestion:
    image: your-dockerhub-username/rust-ingestion:latest
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bitcoin_explorer
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
